version: '3.7'
services:
  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/redpanda:v21.11.15
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://redpanda:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "tglc1996"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
  net-estimator:
    container_name: net-estimator
    image: net-estimator:latest
    environment:
      NEW_USERS: "True"
    ports:
      - "7226:7226"
  net-sender:
    container_name: net-sender
    image: net-sender:latest
  net-reader:
    container_name: net-reader
    image: net-reader:latest
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  metabase:
    container_name: metabase
    image: metabase-with-clickhouse:latest
    ports:
      - "3000:3000"
volumes:
  redpanda-data:
    external: true
  postgres-data:
    external: true