version: '3.7'
services:
  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/redpanda:v21.11.15
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://redpanda:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "tglc1996"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  net-sender:
    container_name: net-sender
    image: net-sender:latest
  net-reader:
    container_name: net-reader
    image: net-reader:latest
  net-analyzer:
    container_name: net-analyzer
    image: net-analyzer:latest
volumes:
  redpanda-data:
    external: true